// flow-typed signature: 5bb809cec9352be9e36e50afbdd5048a
// flow-typed version: <<STUB>>/@expo/vector-icons_v^4.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/vector-icons/createIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromFontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromIcoMoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/iconFontSources' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/App' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/website/src/index' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Zocial' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/vector-icons/createIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSet'>;
}
declare module '@expo/vector-icons/createIconSetFromFontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromFontello'>;
}
declare module '@expo/vector-icons/createIconSetFromIcoMoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromIcoMoon'>;
}
declare module '@expo/vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Entypo'>;
}
declare module '@expo/vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/EvilIcons'>;
}
declare module '@expo/vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/FontAwesome'>;
}
declare module '@expo/vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Foundation'>;
}
declare module '@expo/vector-icons/iconFontSources.js' {
  declare module.exports: $Exports<'@expo/vector-icons/iconFontSources'>;
}
declare module '@expo/vector-icons/index' {
  declare module.exports: $Exports<'@expo/vector-icons'>;
}
declare module '@expo/vector-icons/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons'>;
}
declare module '@expo/vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Ionicons'>;
}
declare module '@expo/vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialIcons'>;
}
declare module '@expo/vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Octicons'>;
}
declare module '@expo/vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/website/src/App.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/App'>;
}
declare module '@expo/vector-icons/website/src/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons/website/src/index'>;
}
declare module '@expo/vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Zocial'>;
}
